POST https://my-expending-project.rj.r.appspot.com/enter_salary
Content-Type: application/json

{
    "salary": 9031.45
}

###
POST http://0.0.0.0:8080/enter_salary
Content-Type: application/json

{
    "salary": 1000
}

###
###
GET http://0.0.0.0:8080/current_salary

###
GET https://my-expending-project.rj.r.appspot.com/current_salary