GET http://0.0.0.0:8080/compulsions_options

###
GET https://my-expending-project.rj.r.appspot.com/compulsions_options

###
GET http://0.0.0.0:8080/lifecost_options

###
GET https://my-expending-project.rj.r.appspot.com/lifecost_options

###
GET http://0.0.0.0:8080/additional_expenses_options

###
GET https://my-expending-project.rj.r.appspot.com/additional_expenses_options

###
POST https://my-expending-project.rj.r.appspot.com/refresh_config

###
POST http://0.0.0.0:8080/refresh_config