POST https://my-expending-project.rj.r.appspot.com/unecessary_delivery
Content-Type: application/json

{
    "value": "55"
}


###
POST https://my-expending-project.rj.r.appspot.com/energy_drink
Content-Type: application/json

{
    "date": "2023-08-30"
}

###
GET https://my-expending-project.rj.r.appspot.com/options_v2


###
POST http://0.0.0.0:8080/energy_drink
Content-Type: application/json

{
    "date": "2023-08-30"
}

###
POST http://0.0.0.0:8080/internet

###
GET http://0.0.0.0:8080/options_v1

###
GET http://0.0.0.0:8080/options_v2

###
POST http://0.0.0.0:8080/refresh
Content-Type: application/json

{
    "month": 9
}

###
POST http://0.0.0.0:8080/unecessary_sweet
Content-Type: application/json

{
    "value": 12.0
}

###
POST http://0.0.0.0:8080/unecessary_fried_pastry

###
POST http://0.0.0.0:8080/unecessary_delivery
Content-Type: application/json

{
    "value": 55
}

###
POST http://0.0.0.0:8080/unecessary_juice
Content-Type: application/json

{
    "value": 55
}

###
POST http://0.0.0.0:8080/life_cost_item
Content-Type: application/json

{
    "value": 30,
    "name": "Life Cost Item",
    "date": "2023-05-04"
}

###
POST http://0.0.0.0:8080/diet_item
Content-Type: application/json

{
    "value": 50,
    "name": "Diet Item",
    "date": "2023-05-04"
}

###
POST http://0.0.0.0:8080/extra_meal
Content-Type: application/json

{
    "value": 60,
    "name": "Extra Meal Item",
    "date": "2023-05-04"
}

###
GET https://60b8-2804-14d-4cd6-ba4c-8cbe-ea28-92cc-90d1.ngrok.io/ping

###
POST https://api.notion.com/v1/databases/33ddadec57b6485faae5a88d6b770141/query
Authorization: Bearer secret_NkGYvmWZ6e0o9Z7CgVys4QDYWuUHkv7wFm3hGVUFycG
Content-Type: application/json
Notion-Version: 2022-06-28

{
   "filter": {
     "and": [
       {
         "property": "Date",
         "date": {
            "after_or_equal": "2023-10-01",
            "before": "2023-11-01"
         }
       }
     ]
   }
 }