POST http://0.0.0.0:3000/energy_drink

###
POST http://0.0.0.0:3000/unecessary_sweet
Content-Type: application/json

{
    "value": 12.0
}

###
POST http://0.0.0.0:3000/unecessary_fried_pastry

###
POST http://0.0.0.0:3000/unecessary_delivery
Content-Type: application/json

{
    "value": 55
}

###
GET https://60b8-2804-14d-4cd6-ba4c-8cbe-ea28-92cc-90d1.ngrok.io/ping